# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.omnifed.hierarchical.communicator import global_grpc_pb2 as src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/omnifed/hierarchical/communicator/global_grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CentralServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendUpdate = channel.unary_unary(
                '/src.omnifed.hierarchical.communicator.CentralServer/SendUpdate',
                request_serializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ModelUpdate.SerializeToString,
                response_deserializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.GetUpdatedModel = channel.unary_unary(
                '/src.omnifed.hierarchical.communicator.CentralServer/GetUpdatedModel',
                request_serializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.GetModelRequest.SerializeToString,
                response_deserializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ModelParameters.FromString,
                _registered_method=True)
        self.RegisterClient = channel.unary_unary(
                '/src.omnifed.hierarchical.communicator.CentralServer/RegisterClient',
                request_serializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ClientInfo.SerializeToString,
                response_deserializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.RegistrationResponse.FromString,
                _registered_method=True)


class CentralServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpdatedModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendUpdate,
                    request_deserializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ModelUpdate.FromString,
                    response_serializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.UpdateResponse.SerializeToString,
            ),
            'GetUpdatedModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdatedModel,
                    request_deserializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.GetModelRequest.FromString,
                    response_serializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ModelParameters.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ClientInfo.FromString,
                    response_serializer=src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.RegistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.omnifed.hierarchical.communicator.CentralServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.omnifed.hierarchical.communicator.CentralServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CentralServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.omnifed.hierarchical.communicator.CentralServer/SendUpdate',
            src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ModelUpdate.SerializeToString,
            src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpdatedModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.omnifed.hierarchical.communicator.CentralServer/GetUpdatedModel',
            src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.GetModelRequest.SerializeToString,
            src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ModelParameters.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.omnifed.hierarchical.communicator.CentralServer/RegisterClient',
            src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.ClientInfo.SerializeToString,
            src_dot_omnifed_dot_hierarchical_dot_communicator_dot_global__grpc__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
